# This is a Spack Environment file.
spack:
  specs:
  - slate
  - blaspp
  - lapackpp
  - magma
  - papi
  - heffte
  - parsec
  view: false
  concretizer:
    unify: true
  packages:
    all:
      variants: [ +cuda, cuda_arch=70 ]
      compiler: [ gcc@12 ]

