# This is a Spack Environment file.
spack:
  specs:
  - slate
  - blaspp
  - lapackpp
  - papi
  - magma
  - heffte
  - parsec
  view: false
  concretizer:
    unify: true
  packages:
    all:
      require:
      - '%COMPILER'
    gcc-runtime:
      require: '%gcc'
    bison:
      require: '%gcc'
