#!/bin/bash -e

set +x
trap 'echo "# $BASH_COMMAND"' DEBUG

DEVICE=$1
COMPILER=$2

source /etc/profile.d/modules.sh
export MODULEPATH=/apps/spacks/current/share/spack/modules/linux-rocky9-x86_64

git clone https://github.com/spack/spack
source spack/share/spack/setup-env.sh

module load gcc@12
if [ "$COMPILER" = "oneapi" ]; then
   module load intel-oneapi-compilers@2022
fi
spack compiler find

if [ "$DEVICE" = "gpu_nvidia" ]; then
   ACCEL="-cuda"
elif [ "$DEVICE" = "gpu_amd" ]; then
   ACCEL="-rocm"
elif [ "$DEVICE" = "gpu_intel" ]; then
   ACCEL="-sycl"
fi

spack env create iSDK ../env-$COMPILER$ACCEL.yaml
spack env activate iSDK

if [ "$DEVICE" = "gpu_amd" ]; then
   # Add local ROCm as external dependencies
   ROCM_VER=$(ls -d /opt/rocm-* | sed 's/.*-//')
   if [ ! -z "$ROCM_VER" ]; then
      sed -e /ROCM_VER/$ROCM_VER/ rocm-packages.yaml > spack/etc/spack/packages.yaml
   fi
fi


spack install --fail-fast

