name: ICL projects

on:
  push:
  workflow_dispatch:

jobs:
  papi:
    strategy:
      matrix:
        include:
          - device: cpu_intel
            spec: +lmsensors +powercap +rapl +sde
          - device: infiniband
            spec: +infiniband
          - device: gpu_nvidia
            spec: +cuda +nvml
          - device: gpu_amd
            spec: +rocm +rocm_smi +rocp_sdk amdgpu_target=gfx906 ^hip@6.3.2
      fail-fast: false
    runs-on: ${{matrix.device}}
    env:
      SPEC: papi@master ${{matrix.spec}}
      COMPILER: gcc@11
      SPACK: "-b gragghia/papi_rocp_sdk https://github.com/G-Ragghianti/spack/"
    steps:
      - uses: actions/checkout@v4
      - run: .github/workflows/spack.sh
      - run: |
             source spack/share/spack/setup-env.sh
             spack load papi
             papi_component_avail

  slate:
    name: ${{matrix.package}} ${{matrix.variants}} ${{matrix.compiler}}
    strategy:
      matrix:
        package: [ slate@master, slate ]
        compiler: [ gcc@11, gcc@12, gcc@13, gcc@14 ]
        device: [ cpu, gpu_nvidia, gpu_amd ]
        include:
          - device: gpu_nvidia
            variants: +cuda cuda_arch=70
          - device: gpu_amd
            variants: +rocm amdgpu_target=gfx906
      fail-fast: false
    runs-on: ${{matrix.device}}
    env:
      SPEC: ${{matrix.package}} ${{matrix.variants}} 
      COMPILER: ${{matrix.compiler}}
    steps:
      - uses: actions/checkout@v4
      - run: .github/workflows/spack.sh
