#!/bin/bash -e

SPEC=$1

source /etc/profile.d/modules.sh
export MODULEPATH=/apps/spacks/current/share/spack/modules/linux-rocky9-x86_64
source spack/share/spack/setup-env.sh

if [ "$COMPILER" = "oneapi" ]; then
   module load intel-oneapi-compilers
else
   module load gcc@12
fi
spack compiler find
spack compiler list

spack spec $SPEC %$COMPILER

