# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:          
  spack:
    strategy:
      matrix:
        spec: 
          - slate
          - blaspp
#          - lapackpp
#          - papi
#          - magma
#          - plasma
#          - heffte
#          - hpcc
#          - parsec
        device: [cpu, gpu_nvidia]
        compiler: [gcc, oneapi]
        exclude:
          - spec: plasma
            device: gpu_nvidia
          - spec: magma
            device: cpu
          - spec: hpcc
            device: gpu_nvidia
      fail-fast: false
    runs-on: ${{ matrix.device }}
    env:
      SPEC:     ${{matrix.spec}}
      DEVICE:   ${{matrix.device}}
      COMPILER: ${{matrix.compiler}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Spack
        run: git clone https://github.com/spack/spack
      - name: Install package
        run: source spack/share/spack/setup-env.sh && \
             spack spec $SPEC %$COMPILER
