# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  m:
    strategy:
      matrix:
        maker: [make, cmake]
        device: [gpu_nvidia, gpu_amd]
        blas: [mkl, mkl-ilp64, openblas]
        compiler: [gcc, intel]
        exclude:
          - maker: make
            device: gpu_amd
          - maker: cmake
            blas: mkl-ilp64
      fail-fast: false
    runs-on: ${{ matrix.device }}
    env:
      MAKER:    ${{matrix.maker}}
      DEVICE:   ${{matrix.device}}
      BLAS:     ${{matrix.blas}}
      COMPILER: ${{matrix.compiler}}
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        run: .github/workflows/generate.sh
      - name: Configure
        run: .github/workflows/configure.sh
      - name: Build
        run: .github/workflows/build.sh
      - name: Test
        run: .github/workflows/test.sh
