
name: CI

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: .github/workflows/

jobs:
  spack:
    strategy:
      matrix:
        device: [cpu, gpu_nvidia]
        compiler: [gcc, oneapi]
      fail-fast: false
    runs-on: ${{ matrix.device }}
    env:
      DEVICE:   ${{matrix.device}}
      COMPILER: ${{matrix.compiler}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Spack
        run: git clone https://github.com/spack/spack
      - run: ./install slate
        if: ${{ ! cancelled() }}
     - run: ./install blaspp
        if: ${{ ! cancelled() }}
