name: papi

on:
  push:
  workflow_dispatch:

jobs:
  sdk:
    strategy:
      matrix:
        device: [cpu_intel]
        compiler: [gcc, oneapi]
        include:
          - device: gpu_nvidia
            spec: +cuda+nvml
          - device: gpu_amd
            spec: +rocm+rocm_smi+rocp_sdk
      fail-fast: false
    runs-on: ${{matrix.device}}
    env:
      SPEC: papi@master ${{matrix.spec}}
      COMPILER: ${{matrix.compiler}}
      SPACK: "-b gragghia/papi_rocp_sdk https://github.com/G-Ragghianti/spack/"
      KEY: /apps/spacks/spack-signing-key
    steps:
      - uses: actions/checkout@v4
      - run: .github/workflows/spack.sh
