name: sdk

on:
#  push:
#    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: CI/

jobs:
  sdk:
    strategy:
      matrix:
        device: [cpu, gpu_nvidia, gpu_amd]
        compiler: [gcc, oneapi]
      fail-fast: false
    runs-on: ${{matrix.device}}
    steps:
      - uses: actions/checkout@v4
      - run: ./sdk ${{matrix.device}} ${{matrix.compiler}}
