name: sdk

on:
#  push:
#    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sdk:
    strategy:
      matrix:
        device: [cpu_intel, cpu_amd, gpu_nvidia, gpu_amd, gpu_intel]
        compiler: [gcc, oneapi]
        exclude:
          - device: gpu_intel
            compiler: gcc
      fail-fast: false
    runs-on: ${{matrix.device}}
    steps:
      - uses: actions/checkout@v4
      - run: ./sdk ${{matrix.device}} ${{matrix.compiler}}
